### ISSUE TITLE
Support external: the same way as module:

### ISSUE THREAD

**Issue by checat** [Kuniwak/jsdoctypeparser#11]
http://usejsdoc.org/tags-external.html shows examples for namepaths like `external:String#rot13`

Generally, it seems JSDoc handles `external:` the same way as `module:`, creating proper references from `@param` etc

> The @external tag identifies a class, namespace, or module that is defined outside of the current package.

`parse()` currently accepts `module:my/pants.Jeans` but does not accept `external:my/pants.Jeans`

Dependent bug: jscs-dev/jscs-jsdoc#88

**Comment by Kuniwak** [comment]
Sorry for my late reply, @checat.

At first, I'm gonna accept `external:` prefix after v2.0.0.

But I do not understand what difference exist between `module:` and `external:`.
This matter is important because the difference strongly affect to the AST spec.

Would you tell me the difference, please?

**Comment by checat** [comment]
I think, for the purposes of type's namepath parsing/validation the `external:` prefix should be treated exactly like `module:`.
The semantic difference is that the name under the `external:` may be anything defined outside of current module/package, like these: external or built-in module, namespace, constructor, global object etc. It's expected that "current" package will declare the symbol with `@external` in some unbound jsdoc comment.

**Comment by Kuniwak** [comment]
Thanks, @checat!

I decide to distinguish AST nodes for `external:` and `module:`.
It make to be open to the interpretation.

**Comment by Kuniwak** [comment]
The feature was released with v2.0.0-alpha.
See [online demo](http://kuniwak.github.io/jsdoctypeparser/).
