### ISSUE TITLE
Support names in form module:my-module

### ISSUE THREAD

**Issue by checat** [Kuniwak/jsdoctypeparser#12]
It appears `module:mymodule` is supported, but `module:my-module` is not.

**Comment by Kuniwak** [comment]
Thanks for your reporting, @checat .

I'm gonna enable it on v2.0.0 (related 9e60e6d).
And after v2.0.0, we can get new AST that is not comatible to v1.x.

**Comment by Kuniwak** [comment]
I was able to enable it on v1.2.0.
