### ISSUE TITLE
2D array @params support

### ISSUE THREAD

**Issue by zxqfox** [Kuniwak/jsdoctypeparser#14]
```
/**
 * @param {number[][]} matrix
 */
```

Refs:
jsdoc3/jsdoc#705
jscs-dev/jscs-jsdoc#94

**Comment by Kuniwak** [comment]
Oops, it is a bug.
I'm working on #10, but the changes will break the backword compatibility.
Now, I'm gonna implement a converter class for old style results.

**Comment by zxqfox** [comment]
@Kuniwak Hey there. Can I help you with that somehow?

**Comment by Kuniwak** [comment]
@zxqfox 
I apologize for worrying you.

I implemented the new parser, and now, I'm preparing publish v1.2.0-alpha and v2.0.0.

In v2.0.0, we can get new AST.
In v1.2.0, we can get results that is equivalent to v1.1.4, but it using the new parser and transform it to legacy.

**Comment by zxqfox** [comment]
Great work! Thank you!

Going to try it :smirk_cat:

**Comment by Kuniwak** [comment]
Resoved on #10.
