### ISSUE TITLE
What about supporting JSDuck literal primitives under option?

### ISSUE THREAD

**Issue by zxqfox** [Kuniwak/jsdoctypeparser#16]
I've got a request about this. What you think about it? Can we make an option?

Spec https://github.com/senchalabs/jsduck/wiki/Type-Definitions#type-names
Ref jscs-dev/jscs-jsdoc#136

**Comment by zxqfox** [comment]
Thanks! ;-)

**Comment by zxqfox** [comment]
Sorry for reopening that, but... Can we store the delimiter in AST? In jscs-jsdoc we need it to prevent using mixed types like `"A"/string|boolean`.

**Comment by Kuniwak** [comment]
OK, I'm gonna add it.

**Comment by Kuniwak** [comment]
Now, we can get syntax info via `meta` properties.

```javascript
{
  "type": "UNION",
  "left": node,
  "right": node,
  "meta": {
    "syntax": "PIPE"
  }
}
```

```javascript
{
  "type": "GENERIC",
  "subject": node,
  "objects": [
    node,
    node,
    ...
  ],
  "meta": {
    "syntax": "ANGLE_BRACKET_WITH_DOT"
  }
}
```

**Comment by zxqfox** [comment]
Oh, sorry for long delay. Thanks!

Need to find some time to use 2.x branch ;-(
