### ISSUE TITLE
Deprecate .toHTML method

### ISSUE THREAD

**Issue by Kuniwak** [Kuniwak/jsdoctypeparser#17]
I want to deprecate `.toHTML` method on v2.x.
This method is not useful, because this spec highly depend on the HTML markup.

**Comment by zxqfox** [comment]
:+1: Would be nice to have a separate project with the current toHTML behaviour and possibility to override templates for entities.
E.g. via set of templates for https://github.com/bem/bh or something like that.

**Comment by Kuniwak** [comment]
I implemented the [`publish` function](https://github.com/Kuniwak/jsdoctypeparser/pull/18/files#diff-f9a0109576d6e18cbd48e74bf657a8b4) to replace `.toHtml()`.
This function take 2 args (an AST node and publisher object).

We can use the function to stringify a node:

```javascript
var string = publish(node);
var string = publish(node, customPublisher);
```
 
The custom publisher object should have the following structure:

```typescript
interface Publisher {
  NodeTypeFoo: function(fooNode: Node, publisher: (node: Node) => string): string,
  NodeTypeBar: function(barNode: Node, publisher: (node: Node) => string): string,
  ...
}
```

Example:

```javascript
    UNION: function(unionNode, publish) {
      return util.format('(%s|%s)', publish(unionNode.left), publish(unionNode.right));
    },
```

How do you feel about this?

**Comment by zxqfox** [comment]
In that way it's very close to BH, just with another syntax. Would be also great to have default node handler or just one handler.

Like:
```
var string = publish(node, Function /* default */ ); // or
var string = publish(node, { default: Function, NodeType1: Function, ... } );
```

**Comment by Kuniwak** [comment]
@zxqfox OK, would you show the concrete example please?

In my implementation, I intended to do it:

```javascript
const {publish, defaultPublisher} = require('jsdoctypeparser');

const string = publish(node, Object.create(defaultPublisher, {
  NodeType1: (node, publish) => {
    return // something
  },
}));
```

**Comment by zxqfox** [comment]
If AST looks like:
```
{ type: 'something', // special key
  somekey: 'and value',
  body: [ // another special key for inner content
    { type: 'another', body: 'array or string or empty' }
  ]
}
```
Then this tree can be traversed (like you do in publish). Exactly this can be done with any declarative template engine. Starting with xjst (xslt analogue), or bh (it uses bemjson formatted structures to generate html: type → block, body → content, all the rest are the same), ending with custom implementations like your publish ;-)

But I think it's possible and very useful to have this (especially if we moving out toHTML). :+1: at all.

**Comment by Kuniwak** [comment]
Do you mean a `traverse` function?

The function is already implemented on [`lib/traversing.js`](https://github.com/Kuniwak/jsdoctypeparser/blob/master/lib/traversing.js#L7).

When I implemented the publishing system, I wanted a publishing system that have no side-effects. It make test easy. So current implementation of `publish` have no side-effects.

If more complex publishing needed, we can implemented it by using `traverse`.

**Comment by zxqfox** [comment]
Yeah, that's great.

**Comment by Kuniwak** [comment]
Thanks for your advice, @zxqfox .
