### ISSUE TITLE
Some parsing confuses

### ISSUE THREAD

**Issue by zxqfox** [Kuniwak/jsdoctypeparser#7]
`Promise*Error` — it produces structure for `Promise|*|Error`. Is it right?

**Comment by Kuniwak** [comment]
@zxqfox Thanks for reporting.

I think it should throw `SyntaxError`.
How about you?

**Comment by zxqfox** [comment]
Definitely! :+1: to `SyntaxError`

**Comment by Kuniwak** [comment]
OK, I'll try to fix it.

**Comment by Kuniwak** [comment]
I'm trying to use PEG (Parser Expression Grammar) to prevent this kind of bug on #10.
But I have a hard time with left recursion...

It may take a little time... :persevere:

**Comment by Kuniwak** [comment]
Resoved on #10.
