### ISSUE TITLE
Infinity loops on incorrect nested brackets closing

### ISSUE THREAD

**Issue by Maqentaer** [Kuniwak/jsdoctypeparser#9]
how to reproduce:
```
var Parser = require('jsdoctypeparser').Parser;
var parser = new Parser();
var result = parser.parse('Array.<Array.<String}>'); // hangs here
```

other problem strings:
`{test: function(Function}`
`{test: Array.<String}`
`{test: Array.<String}>}`

**Comment by Kuniwak** [comment]
I'm trying to use PEG (Parser Expression Grammar) to prevent this kind of bug on #10.
But I have a hard time with left recursion...

It may take a little time... :persevere:

**Comment by Kuniwak** [comment]
Resoved on #10.
